version: '1'

services:

  receiver:
    build:
      context: .
      dockerfile: rabbitmq-w-spring-receiver/Dockerfile
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/payment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_DATASOURCE.DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    ports:
      - 8080:8080

  sender:
    build:
      context: .
      dockerfile: rabbitmq-w-spring-sender/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mysql
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=order
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=root
    ports:
      - 8090:8080

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
        - 27017:27017

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=payment
    ports:
      - 3306:3306